spring:
  application:    name: micro-distancia
  datasource:
    url: jdbc:mysql://localhost:3306/db_distancia?serverTimezone=America/Argentina/Buenos_Aires
    username: root
    password: sasa
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      hibernate:
        SQL: debug
service-distancia:
  url: https://restcountries.eu/rest/v2/
service-country:
  url: https://api.ip2country.info/ip? 
service-moneda:
  url: http://localhost:8082/
service-stats:
  url: http://localhost:8085/  